# Generated by Django 2.2.2 on 2019-06-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planocomissoes',
            name='porcentagem_maior',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='planocomissoes',
            name='porcentagem_menor',
            field=models.IntegerField(),
        ),
    ]
