# Generated by Django 2.2.2 on 2019-07-05 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoComissoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('porcentagem_menor', models.IntegerField()),
                ('valor_minimo', models.FloatField(max_length=20)),
                ('porcentagem_maior', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('cep', models.IntegerField()),
                ('logradouro', models.CharField(max_length=200, verbose_name='Logradouro')),
                ('numero_casa', models.CharField(max_length=50, verbose_name='Número da Casa')),
                ('bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='UF')),
                ('telefone', models.CharField(max_length=50, verbose_name='Telefone')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plano_de_comissoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='televendas.PlanoComissoes')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(choices=[('1', 'Janeiro'), ('2', 'Fevereiro'), ('3', 'Março'), ('4', 'Abril'), ('5', 'Maio'), ('6', 'Junho'), ('7', 'Julho'), ('8', 'Agosto'), ('9', 'Setembro'), ('10', 'Outubro'), ('11', 'Novembro'), ('12', 'Dezembro')], max_length=2, verbose_name='Mês')),
                ('ano', models.CharField(max_length=4, verbose_name='Ano')),
                ('valor_vendas', models.FloatField(max_length=20, verbose_name='Valor das Vendas')),
                ('valor_comissao', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Valor da Comissão')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='televendas.Vendedor')),
            ],
        ),
    ]
