# Generated by Django 2.2.2 on 2019-07-03 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoComissoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentagem_menor', models.IntegerField()),
                ('valor_minimo', models.FloatField(max_length=20)),
                ('porcentagem_maior', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cep', models.IntegerField()),
                ('logradouro', models.CharField(max_length=200)),
                ('numero_casa', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=10)),
                ('cidade', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=10)),
                ('telefone', models.CharField(max_length=20)),
                ('idade', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plano_de_comissoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='televendas.PlanoComissoes')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(choices=[('1', 'Janeiro'), ('2', 'Fevereiro'), ('3', 'Março'), ('4', 'Abril')], max_length=2)),
                ('ano', models.CharField(max_length=4)),
                ('valor_vendas', models.FloatField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='televendas.Vendedor')),
            ],
        ),
    ]
